### ISSUE TITLE
Avoid reload of existing Panes when adding or deleting.

### ISSUE THREAD

**Issue by arivero** [vue-hxs/vue-split-layout#16]
Non propagation of the keys causes reload of Panes. 

This is avoided changing

` return (<div key={i} src-view={'view-' + i}> {view} </div>)`

by 

`return (<div key={view.key} src-view={'view-' + i}> {view} </div>)`

 as implemented by example in this commit https://github.com/vue-hxs/vue-split-layout/pull/13

**Comment by J-Rojas** [comment]
This PR has now been merged. Thanks for bringing this up!
