### ISSUE TITLE
Whether the handle of the drag can be distributed according to the slot

### ISSUE THREAD

**Issue by zhump** [vue-hxs/vue-split-layout#4]
hi 
Whether the handle of the drag can be distributed according to the vue slot ?
I need to customize the style of draggable objects...

**Comment by stdiopt** [comment]
Not sure if I understood the question, in the demo there is a raw pane which can be dragged by starting anywhere in the pane, would that be your goal?

**Comment by stdiopt** [comment]
I made some changes, any element containing pane-drag as attribute will be able to drag the view, updated demo as well, I'm not sure if this will be the final solution, but let me know if works well for you

```html
<!-- as a view on a Layout -->
 <div class="custom-drag">
     <div class="container">
            testing a drag handle
            <div class="drag-handle" pane-drag>DRAG HERE</div>
            test
     </div>
</div>
...
```

**Comment by zhump** [comment]
Thank you for your support. It really helped me. Thank you very much.
