### ISSUE TITLE
input element with v-model will lose focus on every typing

### ISSUE THREAD

**Issue by zenchanhk** [vue-hxs/vue-split-layout#5]
Hi,

I encountered a weird behavior when putting an `input` element inside a pane, the input element loses focus on every typing. But if that input element is without `v-model`, it behaves as usual. Could you please look into it?
`<Pane title="Miscellaneous"><input v-model='value'/></Pane>`

**Comment by stdiopt** [comment]
Just checked it seems to happen when the v-model is on the same level as the layout, if you have a component with v-model it will work (as the demo) if you want to use that, meanwhile I will find out what can be done to solve that

**Comment by zenchanhk** [comment]
Thanks for your info. I will figure out another way to do it.
